name: Node CI

on: push

jobs:
  unit-test:
    runs-on: ubuntu-18.04
    steps:
      upload-to-codecov:
      needs: [frontend-tests, backend-tests]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Download artifacts
          uses: actions/download-artifact@v2
        - name: Upload to Codecov
          uses: codecov/codecov-action@v2
